const LOCALE = "ru";
const STRINGS = {
    error_alert: "Ошибка!",
    success_alert: "Успех!",
    register_username_constraints: "Имя пользователя может содержать только латинские буквы, цифры и знак подчёркивания, длина 3-45 символов",
    register_password_constraints: "Пароль должен содержать как минимум по одной букве в верхнем и нижнем регистре, одну цифру, длина 6-60 символов",
    register_password_not_match: "Пароли не совпадают.",
    register_email_invalid: "Неверный формат почтового адреса.",
    question_edit_success_message: "Вопрос успешно изменён.",
    question_title_empty: "Поле заголовка вопроса должно содержать как минимум одно слово.",
    question_title_too_long: "Максимальная длина заголовка вопроса - 200 символов. Вы написали - ",
    question_description_empty: "Поле описания вопроса должно содержать как минимум одно слово.",
    question_description_too_long: "Максимальная длина описания вопроса - 2000 символов. Вы написали - ",
    question_delete_warning_title: "Удалить данный вопрос?",
    question_delete_warning_message: "Вы действительно хотите удалить данный вопрос? Операцию будет невозможно отменить.",
    question_delete_button_confirm: "Удалить",
    question_delete_button_cancel: "Отмена",
    answer_edit_success_message: "Ответ успешно изменён.",
    answer_text_empty: "Текст ответа должен содержать как минимум одно слово.",
    answer_text_too_long: "Максимальная длина текста ответа - 2000 символов. Вы написали - ",
    answer_delete_warning_title: "Удалить данный ответ?",
    answer_delete_warning_message: "Вы действительно хотите удалить данный ответ? Операцию будет невозможно отменить.",
    answer_delete_button_confirm: "Удалить",
    answer_delete_button_cancel: "Отмена",
    answer_count_multiple: "Ответов",
    answer_count_alter: "Ответа",
    answer_count_single: "Ответ",
    profile_button_ban: "Заблокировать",
    profile_button_unban: "Разблокировать",
    profile_ban_success_message: "Пользователь успешно заблокирован.",
    profile_unban_success_message: "Пользователь успешно разблокирован."
};
Object.freeze(STRINGS);